import NavBar from "@/components/NavBar";
import type { Metadata } from "next";
import { EB_Garamond, Nunito_Sans } from "next/font/google";
import "./globals.css";

const nunito = Nunito_Sans({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const garamond = EB_Garamond({
  variable: "--font-garamond",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${garamond.variable} ${nunito.variable}  antialiased `}>
        <NavBar />
        <div className="pt-24"> {children}</div>
      </body>
    </html>
  );
}
